### ISSUE TITLE
排行榜查询页面

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [Moonlark-Dev/moonlark-frontend#3]
在 `/ranking` 中提供获取 Moonlark 排行榜的方法。

> 如 FTT Points 排行的数据获取地址为: [`https://moonlark-api.itcdt.top/api/rankings/ftt`][1]

配合 Moonlark-Dev/Moonlark#160 工作，支持在排行榜上方显示当前登录用户的排名（如果有）。

[1]: https://moonlark-api.itcdt.top/api/rankings/ftt

**Comment by WowStarWorld** [comment]
Pull https://github.com/Moonlark-Dev/moonlark-frontend/pull/5
